.TH "MainWindow" 3 "Mon Sep 24 2018" "Version 1.0.0" "SaMac" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=nullptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file mainwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SaMac from the source code\&.
