.TH "SaSELinux" 3 "Mon Sep 24 2018" "Version 1.0.0" "SaMac" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaSELinux \- The \fBSaSELinux\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SASELib\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSaSELinux\fP ()"
.br
.RI "\fBSaSELinux\fP constructor\&. "
.in -1c
.SH "Detailed Description"
.PP 
The \fBSaSELinux\fP class\&. 
.PP
Definition at line 7 of file SASELib\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SaMac from the source code\&.
